server:
  port: 8013
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hgq0916/cloud-config-study.git
          username:
          password:
          #/dev
          search-paths: '{profile}'
      #label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8011/eureka/
